### ISSUE TITLE
I_SignalHandler: Signal 11

### ISSUE THREAD

**Issue by f0rttnite** [sultim-t/prboom-plus-rt#12]
No matter what WAD I use and where I place it, PrBoom always crashes before even loading the title screen with an "Exiting on signal: signal 11" error.
Looking it up doesn't really give me any solutions (despite this being a thing in PrBoom for years)

**Comment by neekfenwick** [comment]
I also get this error message, and I have an AMD graphics card (RX6800).  I note the home page of this repo has a Notes section which contains:
"sadly, it works on Nvidia GPUs; it would be nice if someone will decide to add the AMD GPUs support :)"
I do not know if this error is caused by not having an Nvidia GPU.  Can anyone clarify?
What kind of graphics card do you have?

**Comment by f0rttnite** [comment]
A GTX 1080.
Despite not being an RTX card it *should* still work as it supports all the RTX methods that the actual RTX cards have

**Comment by Wookie2600** [comment]
Created an account just to post.  I was getting this error and once I installed the latest drivers from GeForce Experience app, it's working.

**Comment by arrowgent** [comment]
others have used non GTX cards on windows (nvidia atleast, not AMD)

this is only supported for doom 1 wad currently

**Comment by f0rttnite** [comment]
> Created an account just to post. I was getting this error and once I installed the latest drivers from GeForce Experience app, it's working.

Sadly I seem to be on the latest version, so not sure why it's not working

**Comment by BeermotorWB** [comment]
This is an annoying PRBoom bug/quirk/feature from way back, probably going on ten years or so now. It is a generic segfault error.

I'm getting an immediate segfault on the switch to full screen with both my RX 6800XT and my RTX 3090, both with the most recent drivers.  Testing was performed using the original DOS Doom 1 1.9 release (timestamped May 24 1995 23:09) WAD file to ensure consistency.

**Comment by arrowgent** [comment]
does the latest prboom-plus 2.6.2 work?
https://github.com/coelckers/prboom-plus/releases

the prboom-plus-RT is using 2.6.1 which is only slightly older

worth a test

**Comment by GalmFOx** [comment]
> does the latest prboom-plus 2.6.2 work? https://github.com/coelckers/prboom-plus/releases
> 
> the prboom-plus-RT is using 2.6.1 which is only slightly older
> 
> worth a test

nope

**Comment by sultim-t** [comment]
There's a segfault somewhere... need to use address sanitizer as the starting point

**Comment by Rastommy77** [comment]
I am getting the same error. GTX 1080. 
Downloaded The Ultimate Doom on Steam and created a new folder within. Copied the prt folders contents in there and copied the doom.wad into it. Ran it, then it came up with signal handler error 11

**Comment by sultim-t** [comment]
Hmm.. I wonder if that signal 11 error related to MSI Afterburner / RivaTuner Statistics Server / etc being installed. 

I remember I had a bad time making Serious Sam Ray Traced running while those programs were installed. After I uninstalled them, windowing system error was fixed magically there. There's a small chance that it's the solution

**Comment by lerouxm** [comment]
GTX 1060 / Latest Nvidia drivers : Same issue ! Got no additional software running like AfterBurner or Riva... :(

**Comment by AndrewMRX** [comment]
I have this issue too. I put the configuration file from another version of prboom and it worked. but when I select rt render, it crashes again. GTX 1060 6gb. Latest drivers.

**Comment by ferrellsl** [comment]
Same here.  GTX 1080, latest drivers and tried various WAD files from ver. 1.1, 1.666 thru 1.9.

**Comment by Elizafur** [comment]
Same here on a GTX 1080 TI, tried using the included 2.6.1 prboom and 2.6.2 but no luck.

**Comment by German-S** [comment]
I think it's worth releasing this on another engine, because PrBoom has problems that make it impossible to run.

**Comment by lafoxxx92** [comment]
> I think it's worth releasing this on another engine, because PrBoom has problems that make it impossible to run.

Considering it works for them, why would they? It's usually easier to fix the issue than to start over in different port.

BTW, I also have this issue and can provide all info needed to resolve it (just tell me what's needed).

**Comment by sultim-t** [comment]
Maybe try with `-vidmode GL` argument for the executable

**Comment by AndrewMRX** [comment]
Version 2.6.1 works well.

**Comment by lafoxxx92** [comment]
> Maybe try with `-vidmode GL` argument for the executable

works, stops working with the above error after changing the renderer in options.

**Comment by BeermotorWB** [comment]
> does the latest prboom-plus 2.6.2 work? https://github.com/coelckers/prboom-plus/releases
> 
> the prboom-plus-RT is using 2.6.1 which is only slightly older
> 
> worth a test

Thanks for the link to the new build.  Ran without issue on my AMD and Nvidia GPUs. 
Worth noting that even though it didn't run on the 6800xt and 3090, 


> First thing is to understand if it's related to RT or to prboom itself: if the actual prboom v2.6.1 release works https://github.com/coelckers/prboom-plus/releases/tag/v2.6.1um without such error

This version also ran without the segfault.  

If i can get time I'm planning on testing under Linux with the RADV driver to validate this is related to the issue identified in  #8  

Worth noting for completeness: I did get a successful run to E1M3 on my son's 3060 with Geforce driver v512.15.

**Comment by German-S** [comment]
> Maybe try with `-vidmode GL` argument for the executable

The latest PrBoom works without problems. 
As well as the current PrBoom with the parameter "-vidmode GL" starts and works without RT. 
I don't understand what's wrong, the same Quake 2 RTX runs from steam in RTX mode.

**Comment by sultim-t** [comment]
Since original PrBoom works, then there's some bug in my changes in PrBoom or on RayTracedGL1 side :(
It's tricky to find, would be nice to have some help. I will provide more info on how to build them, so more people can try to find the source of the segfault.

**Comment by planetarian** [comment]
I am also having this issue; playing on my desktop with a GTX 1080 gets a Signal 11 error unless I launch in GL mode. Switching to RT mode once in-game doesn't seem to do anything noticeable. A normal instance of PRBoom 2.6.1um works just fine.

**Comment by German-S** [comment]
I think, I wasn't completely honest.
Quake 2 RTX works for me most likely because DXR is implemented there (software implementation of RTX).
This explains why your project may not work for people with video cards based on Pascal architecture.
Now, if you could add DXR to the port ...

**Comment by NadnerbD** [comment]
GTX 1080 user here, also seeing the same error. Runs without RT using `-vidmode GL`, subsequently selecting RT in options doesn't seem to change anything.

**Comment by ColonelPhantom** [comment]
> I think, I wasn't completely honest.
> Quake 2 RTX works for me most likely because DXR is implemented there (software implementation of RTX).
> This explains why your project may not work for people with video cards based on Pascal architecture.
> Now, if you could add DXR to the port ...

Quake 2 RTX doesnt use DXR, it uses Vulkan ray-tracing in the form of VK_KHR_raytracing_pipeline or VK_KHR_ray_query. I'm quite certain the library from the author of this project also uses VK_KHR_raytracing_pipeline.

DXR is also not a software implementation of RTX. Rather, it's a generic API to interact with raytracing hardware, like DirectX (which DXR is an optional part of) is a generic API to interact with graphics hardware in general.

**Comment by arrowgent** [comment]
i have an nvidia 1070, and i can run Q2RTX at 8-10fps.  i do NOT have an RTX capable card

**Comment by Civil** [comment]
>  I will provide more info on how to build them, so more people can try to find the source of the segfault.

[Source of segfault is sort of simple to find.
](https://github.com/sultim-t/RayTracedGL1/blob/SpecularReprojection/Source/Common.h#L71-L74)

You have a check that verifies if Vulkan was initialized. And the problem is that `assert` in non-debug built will be removed and check would be effectively removed from the code. If you don't have a proper Vulkan Surface next time you'll use it, your code will segfault.

I believe that Vulkan initialization logic need to have better error handling and provide verbose information on why it can't initialize vulkan.

**Comment by Orthestral** [comment]
It was working perfectly until today, after I updated my system and restarted. Now it's giving me the Signal 11

**Comment by xlen** [comment]
> i have an nvidia 1070, and i can run Q2RTX at 8-10fps. i do NOT have an RTX capable card

RTX is not a feature... GTX 1060 6GB and above all support RTRT, the performance on Pascal isn't great and nVidia has put no effort into optimizing it in any way.


As for the issue at hand, GTX 1060 6GB here, signal 11 as well, I read in forums something about "textures in the PNG format instead of Doom format could be the problem." related to PRBooM Plus 🤷‍♂️

**Comment by VegaBiggs** [comment]
GTX 1060 6GB here, I have the signal 11 problem on prboom RT but the last vanilla prboom works fine.
512.15 Nvidia Driver.

**Comment by bubbleguuum** [comment]
Same issue:

- GTX 1080 TI
- Windows 11 (Beta)
- NVIDIA Drivers: 512.15

**Comment by NKO55** [comment]
Same issue here.

- GTX 1070 Ti 8 gb
- Windows 10 (10.0.19041 Build 19041)
- Drivers 512.15
- Using the GoG.com version of Ultimate Doom

Tried running with and without the dlss.dll.

**Comment by InFlamesHell** [comment]
Same here.. GTX 1080
seems like we all have a 10XX in here :P

**Comment by Orthestral** [comment]
> What did you update? What GPU driver version you had and have now?

I didn't update any GPU driver. The most notable package updates were:
- libgcrypt
- X11 Display Server
- Lutris
- Pango
- shared-mime-info
- Wine Mono (.NET)
- zlib
All others are a standalone application or have to do networking or VMs

I use Void Linux and RTX 2070S. I run PRBoom through Lutris

**Comment by xlen** [comment]
> Same here.. GTX 1080 seems like we all have a 10XX in here :P

Most people here seems to have Pascal yes, but not everyone.

**Comment by BoomDoomTomb** [comment]
Same issue. Crash within seconds of starting up the .exe. I_SignalHandler: Exiting on signal: signal 11. I have GTX 1070 ti with latest drivers and Intel Core I7-3770K 16gb DDR3. Tried to Google this error code and it brought me here.

**Comment by CUTWEST** [comment]
At first I was getting the "can't initialize ray tracing engine" error....After I updated my drivers now im getting this error. Cant win for losing on this GTX 1080ti. Maybe its just not compatible with Pascal cards can anyone with a 10xx series card confirm this is even working for them?  So far I see nothing but Pascal owners having this issue while no confirmation of this even working with pascal cards to begin with.

**Comment by xlen** [comment]
> At first I was getting the "can't initialize ray tracing engine" error....After I updated my drivers now im getting this error. Cant win for losing on this GTX 1080ti. Maybe its just not compatible with Pascal cards can anyone with a 10xx series card confirm this is even working for them? So far I see nothing but Pascal owners having this issue while no confirmation of this even working with pascal cards to begin with.

People who have it working aren't looking at the issues section 😅

**Comment by RowanSkie** [comment]
> > At first I was getting the "can't initialize ray tracing engine" error....After I updated my drivers now im getting this error. Cant win for losing on this GTX 1080ti. Maybe its just not compatible with Pascal cards can anyone with a 10xx series card confirm this is even working for them? So far I see nothing but Pascal owners having this issue while no confirmation of this even working with pascal cards to begin with.
> 
> People who have it working aren't looking at the issues section 😅

Or probably is looking but is trying to find another solution to the problem (A GTX 1080ti here, trying to find a solution on other ways atm)

**Comment by Pablossjui** [comment]
I'll add that I also run into this error and I'm using a GTX 1080 Ti (with a Ryzen 5600x)
I'm not sure it's anything related to Vulkan not being able to use the raytracing libraries. I can run this demo no problem https://www.geeks3d.com/dl/show/50110

**Comment by LittleGreenSpaceMan** [comment]
I am getting the same error with my GTX 1080ti, tried the possible solutions in this thread, they didn't work. I am the latest drivers for my card also.

**Comment by MissingNO57** [comment]
Same errorhere with Windows 11 and MSI GTX 1080ti, running NVIDIA drivers 512.15.

**Comment by gitsjd** [comment]
Same issue here on gtx1070. Looks like we're hooped as the dev said it's beyond his scope and time to search for the bug.

**Comment by GitKEKZ** [comment]
> > At first I was getting the "can't initialize ray tracing engine" error....After I updated my drivers now im getting this error. Cant win for losing on this GTX 1080ti. Maybe its just not compatible with Pascal cards can anyone with a 10xx series card confirm this is even working for them? So far I see nothing but Pascal owners having this issue while no confirmation of this even working with pascal cards to begin with.
> 
> People who have it working aren't looking at the issues section 😅

I mean true, why would they hehe
Im getting the same error here too (I_SignalHandler: Exiting on signal: signal 11), wasn't expecting to run well on a 1060 anyway, but i would have enjoyed seeing raytraced doom. Even if its only running at 2FPS :D

**Comment by sultim-t** [comment]
Not sure if related, but I've fixed a double-free bug on Linux in 1.0.4.
Also, I wonder if SEGFAULT (i.e. `signal 11`) is related to upscaling techniques. `prboom-rt-1.0.4-noupscalers.zip` https://github.com/sultim-t/prboom-plus-rt/releases/tag/v2.6.1-rt1.0.4 doesn't have them, so maybe it's worth to check them

**Comment by VanillaDeath** [comment]
> Not sure if related, but I've fixed a double-free bug on Linux in 1.0.4. Also, I wonder if SEGFAULT (i.e. `signal 11`) is related to upscaling techniques. `prboom-rt-1.0.4-noupscalers.zip` https://github.com/sultim-t/prboom-plus-rt/releases/tag/v2.6.1-rt1.0.4 doesn't have them, so maybe it's worth to check them

I'm also experiencing this issue (GTX 1080 on Win11, v512.15). Tried the `noupscalers` version too, same issue, sadly.

**Comment by pulimento** [comment]
@sultim-t just tried the v1.0.4-noupscalers, didn't fix it (same error at startup)
Windows 10, i5 12600k, GTX 1060 6GB, latest NVidia drivers

**Comment by tigrouind** [comment]
I'm getting the same error message with a 1080 Ti and the 512.15 drivers.
It's a bit disappointing that you need an RTX card to get it to work properly, especially since it's technically possible to get RT on such low poly games with reasonably modern GPUs. Check out this [demo] (https://reindernijhoff.net/wolfrt/)

**Comment by gitsjd** [comment]
Same here, 1070 with 5.12.15 drivers.

**Comment by RowanSkie** [comment]
@sultim-t maybe it would be nice to know which shaders are required for PrBoom RT because it seems there's a shader that the app uses that doesn't 1000 series cards don't have but everyone higher else has.

**Comment by py5iu** [comment]
I had high hopes I will be able to play this since I could have fun with Quake 2 RTX but with this Project I am getting the error listed in this thread.
Using 1080TI with latest drivers (tried a few older versions just to be sure as well) on Win10 Pro 64 bit.

**Comment by oMadMartigaNo** [comment]
Same issue ( I_SignalHandler: Exiting on signal: signal 11 ):

- GTX 1080 TI
- Windows 11
- NVIDIA Drivers: v512.15

**Comment by curryking3** [comment]
Also same issue
1080 ti
Windows 11
5950x
Nvidia driver 512.15

I_SignalHandler: Exiting on signal: signal 11

Using the vidmode ogl works but of course disables the RT, and switching in-game or restarting to try RT gives same error

**Comment by ViniciusLCredendio** [comment]
> I'm getting the same error message with a 1080 Ti and the 512.15 drivers. It's a bit disappointing that you need an RTX card to get it to work properly, especially since it's technically possible to get RT on low poly games with old GPUs. Check out this [demo](https://reindernijhoff.net/wolfrt/).

Wow this demo is amazing!! Runs well even on a simple setup.

**Comment by shizukachan** [comment]
https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353

> ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> //vulkan12Features.shaderFloat16 = 1;
> vulkan12Features.shaderFloat16 = 0;

With DLSS=off, should fix Pascal vk device creation

**Comment by gryph-soul** [comment]
> > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > //vulkan12Features.shaderFloat16 = 1;
> > vulkan12Features.shaderFloat16 = 0;
> 
> With DLSS=off, should fix Pascal vk device creation

This error was eliminated on with Pascal video cards ?

**Comment by VanillaDeath** [comment]
> [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> 
> > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > //vulkan12Features.shaderFloat16 = 1;
> > vulkan12Features.shaderFloat16 = 0;
> 
> With DLSS=off, should fix Pascal vk device creation

Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.

**Comment by RowanSkie** [comment]
And now we wait for the PR to go through and for us to finally play nicely raytraced Doom.

**Comment by tigrouind** [comment]
> And now we wait for the PR to go through and for us to finally play nicely raytraced Doom.

I don't see any PR yet.

**Comment by ferrellsl** [comment]
> > [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> > > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > > //vulkan12Features.shaderFloat16 = 1;
> > > vulkan12Features.shaderFloat16 = 0;
> > 
> > 
> > With DLSS=off, should fix Pascal vk device creation
> 
> Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.

Mind sharing the binary with the rest of us?

**Comment by VanillaDeath** [comment]
> > > [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> > > > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > > > //vulkan12Features.shaderFloat16 = 1;
> > > > vulkan12Features.shaderFloat16 = 0;
> > > 
> > > 
> > > With DLSS=off, should fix Pascal vk device creation
> > 
> > 
> > Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.
> 
> Mind sharing the binary with the rest of us?

Here you go! :)

[RayTracedGL1.zip](https://github.com/sultim-t/prboom-plus-rt/files/8594846/RayTracedGL1.zip)

**Comment by gitsjd** [comment]
Now, I get a different error running version 1.0.6, and even when using the RayTracedLG1.dll from VanillaDeath: "Can't initialize ray tracing engine: RG cant find physical device". I'm using a GTX 1070.

**Comment by ferrellsl** [comment]
> > > > [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> > > > > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > > > > //vulkan12Features.shaderFloat16 = 1;
> > > > > vulkan12Features.shaderFloat16 = 0;
> > > > 
> > > > 
> > > > With DLSS=off, should fix Pascal vk device creation
> > > 
> > > 
> > > Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.
> > 
> > 
> > Mind sharing the binary with the rest of us?
> 
> Here you go! :)
> 
> [RayTracedGL1.zip](https://github.com/sultim-t/prboom-plus-rt/files/8594846/RayTracedGL1.zip)

Thanks VanillaDeath!  Works great on my GTX 1080!

**Comment by Pablossjui** [comment]
> > > > > [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> > > > > > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > > > > > //vulkan12Features.shaderFloat16 = 1;
> > > > > > vulkan12Features.shaderFloat16 = 0;
> > > > > 
> > > > > 
> > > > > With DLSS=off, should fix Pascal vk device creation
> > > > 
> > > > 
> > > > Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.
> > > 
> > > 
> > > Mind sharing the binary with the rest of us?
> > 
> > 
> > Here you go! :)
> > [RayTracedGL1.zip](https://github.com/sultim-t/prboom-plus-rt/files/8594846/RayTracedGL1.zip)
> 
> Thanks VanillaDeath! Works great on my GTX 1080!

What build are you using? I'm getting the error Can't Initialize ray tracing engine: RG_WRONG_ARGUMENT

Asus GTX 1080TI here

**Comment by ferrellsl** [comment]
> > > > > > [#74 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/74#issuecomment-1110010353)
> > > > > > > ~/src/prboom-plus-rt/RayTracedGL1/Source/VulkanDevice.cpp
> > > > > > > //vulkan12Features.shaderFloat16 = 1;
> > > > > > > vulkan12Features.shaderFloat16 = 0;
> > > > > > 
> > > > > > 
> > > > > > With DLSS=off, should fix Pascal vk device creation
> > > > > 
> > > > > 
> > > > > Indeed, this was the solution! It works with my GTX 1080, ok framerate at 480p or using AMD FSR Performance mode.
> > > > 
> > > > 
> > > > Mind sharing the binary with the rest of us?
> > > 
> > > 
> > > Here you go! :)
> > > [RayTracedGL1.zip](https://github.com/sultim-t/prboom-plus-rt/files/8594846/RayTracedGL1.zip)
> > 
> > 
> > Thanks VanillaDeath! Works great on my GTX 1080!
> 
> What build are you using? I'm getting the error Can't Initialize ray tracing engine: RG_WRONG_ARGUMENT
> 
> Asus GTX 1080TI here

I'm using the 1.07 pre-release found here:  https://github.com/sultim-t/prboom-plus-rt/releases/tag/v2.6.1-rt1.0.7

**Comment by Pablossjui** [comment]
Yeah that worked! seems like the binary would only work with that build. Shame, it looks like AMD FSR is broken so there's not much performance there to gain

**Comment by RowanSkie** [comment]
Alright, I tried it out, and it works!

Very laggy, but that's expected of a 1080ti card.

**Comment by ferrellsl** [comment]
> Alright, I tried it out, and it works!
> 
> Very laggy, but that's expected of a 1080ti card.

Turn off AMD FSR and your framerate will more than double.

**Comment by RowanSkie** [comment]
> > Alright, I tried it out, and it works!
> > Very laggy, but that's expected of a 1080ti card.
> 
> Turn off AMD FSR and your framerate will more than double.

I went to make it to 300p. I'm honestly no longer that used to 30-60fps gameplay.
EDIT: Turned it to 480p with a few minor settings tweaks, and now it works.

**Comment by Calinou** [comment]
I can confirm the DLL linked above works with 1.0.7 on Linux (using WINE) on a GTX 1080.

AMD FSR works, but it can only be used if you use the native resolution. On a 2560×1440 display, FSR is too slow even with the Performance mode, so using 320×200 or perhaps 480p is a better bet. 320×200 makes it possible to target 60 FPS (often reaching more in practice), and 480p can target 35 FPS if reducing the number of light bounces to 1.

Unfortunately, it's not possible to use *both* resolution scaling and FSR. This could likely be changed, as it's not a technical limitation to my knowledge.

If you have trouble reaching 60+ FPS consistently, I recommend disabling this option in the PrBoom+ general options:

![image](https://user-images.githubusercontent.com/180032/167447843-98db38ca-b780-49a1-a2d3-80163f369bc1.png)

Counterintuitively, disabling uncapped framerate will *reduce* input lag (both mouse and keyboard) if you regularly dip below 60 FPS. This is because the engine will no longer bother doing physics interpolation of any kind, avoiding an one-frame delay that otherwise always occurs when physics interpolation is enabled.

On this GTX 1080, 480p on 16:9, 1 light bounce, uncapped framerate OFF can manage a locked 35 FPS with responsive enough gameplay – as responsive as it is in the original anyway :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/180032/167447135-657aedb5-3890-4789-a617-1f5385044507.png)

**Comment by lerouxm** [comment]
(GTX 10xx) Confirmed working with 1.0.7 and [RayTracedGL1.dll](https://github.com/sultim-t/prboom-plus-rt/files/8594846/RayTracedGL1.zip) replacement. Thanks guys !

**Comment by curryking3** [comment]
Confirming that worked as well, thanks for the help :)

**Comment by DwarfFighterCleric** [comment]
Anyone else with a Ryzen 3000 generation chip? I have a 3500U (Vega 8 - laptop) and I get the same error message, "Can't Find Physical Device"  
I tried the alternative DLL same thing, no help...  
Is my Ryzen 3500 uncapable of having Ray Tracing at all? Or is it something I need to enable with Driver Updates? But I am already using 2022 drivers... I'm confused...

**Comment by DwarfFighterCleric** [comment]
> Now, I get a different error running version 1.0.6, and even when using the RayTracedLG1.dll from VanillaDeath: "Can't initialize ray tracing engine: RG cant find physical device". I'm using a GTX 1070.

same error message here... did you ever found a fix for this? I have AMD Ryzen 3000

**Comment by RowanSkie** [comment]
"RG can't find physical device" happens with a graphics card that doesn't support the RTX 1.0 calls this game uses, I believe.

**Comment by Calinou** [comment]
> Anyone else with a Ryzen 3000 generation chip? I have a 3500U (Vega 8 - laptop) and I get the same error message, "Can't Find Physical Device"

Vega IGPs do not have hardware raytracing support, and the non-RTX fallback may not work on all GPUs (especially slow, integrated GPUs).

That said, I don't think your IGP would be able to deliver a good experience with this mod, even at 320×200 when targeting 35 FPS. The GTX 1060 (a much faster GPU) is already struggling in this situation.

**Comment by courtesysoft** [comment]
Damn i'm so thankful for this little fix. Wish the repo owner would 

On a 1060 i can run 480p and see around 25FPS with 1 light bounce turned on.
~60FPS on 320 x 200 with 2 light sources on, but that's a little too retro today :)
